name: "Asana Prefix Link Action"
description: "Pick up an Asana defined prefix from the PR title and link it in a project"
inputs:
  GITHUB_TOKEN:
    description: "Github Token"
    required: true
  ASANA_CLIENT_ID:
    description: "Asana Client ID"
    required: true
  ASANA_CLIENT_SECRET:
    description: "Asana Client Secret"
    required: true
  ASANA_PROJECT_GID:
    description: "Asana Project GID"
    required: true
runs:
  using: "node16"
  main: "index.js"
