name: Test
on:
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Asana Prefix Action
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          ASANA_CLIENT_ID: ${{secrets.ASANA_CLIENT_ID}}
          ASANA_CLIENT_SECRET: ${{secrets.ASANA_CLIENT_SECRET}}
          ASANA_PROJECT_GID: "1204035711888252"
